[project]
name = "house-buying"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "AloizioMacedo", email = "atsam2@hotmail.com" }]
requires-python = ">=3.13"
dependencies = ["pandas>=2.3.0"]
