[project]
name = "house-buying"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "AloizioMacedo", email = "atsam2@hotmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "pydantic>=2.11.7",
]
